###############################################################################
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml-py
#
###############################################################################

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code.
#
# ruff: noqa: E501,F401
# flake8: noqa: E501,F401
# pylint: disable=unused-import,line-too-long
# fmt: off
from typing import Any, Dict, List, Optional, TypeVar, Union, TypedDict, Type, Literal, cast
from typing_extensions import NotRequired
import pprint

import baml_py
from pydantic import BaseModel, ValidationError, create_model

from . import partial_types, types
from .types import Checked, Check
from .type_builder import TypeBuilder
from .globals import DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_CTX, DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME


OutputType = TypeVar('OutputType')


# Define the TypedDict with optional parameters having default values
class BamlCallOptions(TypedDict, total=False):
    tb: NotRequired[TypeBuilder]
    client_registry: NotRequired[baml_py.baml_py.ClientRegistry]

class BamlAsyncClient:
    __runtime: baml_py.BamlRuntime
    __ctx_manager: baml_py.BamlCtxManager
    __stream_client: "BamlStreamClient"

    def __init__(self, runtime: baml_py.BamlRuntime, ctx_manager: baml_py.BamlCtxManager):
      self.__runtime = runtime
      self.__ctx_manager = ctx_manager
      self.__stream_client = BamlStreamClient(self.__runtime, self.__ctx_manager)

    @property
    def stream(self):
      return self.__stream_client


    
    async def Conversationalist(
        self,
        user_query: str,
        baml_options: BamlCallOptions = {},
    ) -> types.ChatResponse:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = await self.__runtime.call_function(
        "Conversationalist",
        {
          "user_query": user_query,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )
      return cast(types.ChatResponse, raw.cast_to(types, types, partial_types, False))
    
    async def FormatResponse(
        self,
        messages: types.Payload,
        baml_options: BamlCallOptions = {},
    ) -> types.ResponseFormatter:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = await self.__runtime.call_function(
        "FormatResponse",
        {
          "messages": messages,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )
      return cast(types.ResponseFormatter, raw.cast_to(types, types, partial_types, False))
    
    async def Navigate(
        self,
        agent: types.Agent,payload: types.Payload,
        baml_options: BamlCallOptions = {},
    ) -> types.Navigator:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = await self.__runtime.call_function(
        "Navigate",
        {
          "agent": agent,"payload": payload,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )
      return cast(types.Navigator, raw.cast_to(types, types, partial_types, False))
    
    async def ParseQuery(
        self,
        context: types.Payload,
        baml_options: BamlCallOptions = {},
    ) -> types.QueryParser:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = await self.__runtime.call_function(
        "ParseQuery",
        {
          "context": context,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )
      return cast(types.QueryParser, raw.cast_to(types, types, partial_types, False))
    
    async def Respond(
        self,
        inputMessage: types.Payload,workers: List[types.Agent],
        baml_options: BamlCallOptions = {},
    ) -> types.Responder:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = await self.__runtime.call_function(
        "Respond",
        {
          "inputMessage": inputMessage,"workers": workers,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )
      return cast(types.Responder, raw.cast_to(types, types, partial_types, False))
    
    async def RetrieveSchema(
        self,
        user_query: str,db_schema: types.Schema,parsed_query: types.ParsedQuery,
        baml_options: BamlCallOptions = {},
    ) -> types.SchemaMapper:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = await self.__runtime.call_function(
        "RetrieveSchema",
        {
          "user_query": user_query,"db_schema": db_schema,"parsed_query": parsed_query,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )
      return cast(types.SchemaMapper, raw.cast_to(types, types, partial_types, False))
    
    async def SummarizeData(
        self,
        inputMessage: types.Payload,
        baml_options: BamlCallOptions = {},
    ) -> types.DataSummarizer:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = await self.__runtime.call_function(
        "SummarizeData",
        {
          "inputMessage": inputMessage,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )
      return cast(types.DataSummarizer, raw.cast_to(types, types, partial_types, False))
    
    async def Supervise(
        self,
        Messages: types.Payload,workers: List[types.Agent],
        baml_options: BamlCallOptions = {},
    ) -> types.Supervisor:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = await self.__runtime.call_function(
        "Supervise",
        {
          "Messages": Messages,"workers": workers,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )
      return cast(types.Supervisor, raw.cast_to(types, types, partial_types, False))
    
    async def ValidateResponse(
        self,
        inputMessage: types.Payload,
        baml_options: BamlCallOptions = {},
    ) -> types.Validator:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = await self.__runtime.call_function(
        "ValidateResponse",
        {
          "inputMessage": inputMessage,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )
      return cast(types.Validator, raw.cast_to(types, types, partial_types, False))
    


class BamlStreamClient:
    __runtime: baml_py.BamlRuntime
    __ctx_manager: baml_py.BamlCtxManager

    def __init__(self, runtime: baml_py.BamlRuntime, ctx_manager: baml_py.BamlCtxManager):
      self.__runtime = runtime
      self.__ctx_manager = ctx_manager

    
    def Conversationalist(
        self,
        user_query: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[partial_types.ChatResponse, types.ChatResponse]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = self.__runtime.stream_function(
        "Conversationalist",
        {
          "user_query": user_query,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )

      return baml_py.BamlStream[partial_types.ChatResponse, types.ChatResponse](
        raw,
        lambda x: cast(partial_types.ChatResponse, x.cast_to(types, types, partial_types, True)),
        lambda x: cast(types.ChatResponse, x.cast_to(types, types, partial_types, False)),
        self.__ctx_manager.get(),
      )
    
    def FormatResponse(
        self,
        messages: types.Payload,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[partial_types.ResponseFormatter, types.ResponseFormatter]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = self.__runtime.stream_function(
        "FormatResponse",
        {
          "messages": messages,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )

      return baml_py.BamlStream[partial_types.ResponseFormatter, types.ResponseFormatter](
        raw,
        lambda x: cast(partial_types.ResponseFormatter, x.cast_to(types, types, partial_types, True)),
        lambda x: cast(types.ResponseFormatter, x.cast_to(types, types, partial_types, False)),
        self.__ctx_manager.get(),
      )
    
    def Navigate(
        self,
        agent: types.Agent,payload: types.Payload,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[partial_types.Navigator, types.Navigator]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = self.__runtime.stream_function(
        "Navigate",
        {
          "agent": agent,
          "payload": payload,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )

      return baml_py.BamlStream[partial_types.Navigator, types.Navigator](
        raw,
        lambda x: cast(partial_types.Navigator, x.cast_to(types, types, partial_types, True)),
        lambda x: cast(types.Navigator, x.cast_to(types, types, partial_types, False)),
        self.__ctx_manager.get(),
      )
    
    def ParseQuery(
        self,
        context: types.Payload,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[partial_types.QueryParser, types.QueryParser]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = self.__runtime.stream_function(
        "ParseQuery",
        {
          "context": context,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )

      return baml_py.BamlStream[partial_types.QueryParser, types.QueryParser](
        raw,
        lambda x: cast(partial_types.QueryParser, x.cast_to(types, types, partial_types, True)),
        lambda x: cast(types.QueryParser, x.cast_to(types, types, partial_types, False)),
        self.__ctx_manager.get(),
      )
    
    def Respond(
        self,
        inputMessage: types.Payload,workers: List[types.Agent],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[partial_types.Responder, types.Responder]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = self.__runtime.stream_function(
        "Respond",
        {
          "inputMessage": inputMessage,
          "workers": workers,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )

      return baml_py.BamlStream[partial_types.Responder, types.Responder](
        raw,
        lambda x: cast(partial_types.Responder, x.cast_to(types, types, partial_types, True)),
        lambda x: cast(types.Responder, x.cast_to(types, types, partial_types, False)),
        self.__ctx_manager.get(),
      )
    
    def RetrieveSchema(
        self,
        user_query: str,db_schema: types.Schema,parsed_query: types.ParsedQuery,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[partial_types.SchemaMapper, types.SchemaMapper]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = self.__runtime.stream_function(
        "RetrieveSchema",
        {
          "user_query": user_query,
          "db_schema": db_schema,
          "parsed_query": parsed_query,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )

      return baml_py.BamlStream[partial_types.SchemaMapper, types.SchemaMapper](
        raw,
        lambda x: cast(partial_types.SchemaMapper, x.cast_to(types, types, partial_types, True)),
        lambda x: cast(types.SchemaMapper, x.cast_to(types, types, partial_types, False)),
        self.__ctx_manager.get(),
      )
    
    def SummarizeData(
        self,
        inputMessage: types.Payload,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[partial_types.DataSummarizer, types.DataSummarizer]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = self.__runtime.stream_function(
        "SummarizeData",
        {
          "inputMessage": inputMessage,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )

      return baml_py.BamlStream[partial_types.DataSummarizer, types.DataSummarizer](
        raw,
        lambda x: cast(partial_types.DataSummarizer, x.cast_to(types, types, partial_types, True)),
        lambda x: cast(types.DataSummarizer, x.cast_to(types, types, partial_types, False)),
        self.__ctx_manager.get(),
      )
    
    def Supervise(
        self,
        Messages: types.Payload,workers: List[types.Agent],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[partial_types.Supervisor, types.Supervisor]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = self.__runtime.stream_function(
        "Supervise",
        {
          "Messages": Messages,
          "workers": workers,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )

      return baml_py.BamlStream[partial_types.Supervisor, types.Supervisor](
        raw,
        lambda x: cast(partial_types.Supervisor, x.cast_to(types, types, partial_types, True)),
        lambda x: cast(types.Supervisor, x.cast_to(types, types, partial_types, False)),
        self.__ctx_manager.get(),
      )
    
    def ValidateResponse(
        self,
        inputMessage: types.Payload,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[partial_types.Validator, types.Validator]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = self.__runtime.stream_function(
        "ValidateResponse",
        {
          "inputMessage": inputMessage,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )

      return baml_py.BamlStream[partial_types.Validator, types.Validator](
        raw,
        lambda x: cast(partial_types.Validator, x.cast_to(types, types, partial_types, True)),
        lambda x: cast(types.Validator, x.cast_to(types, types, partial_types, False)),
        self.__ctx_manager.get(),
      )
    

b = BamlAsyncClient(DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME, DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_CTX)

__all__ = ["b"]