###############################################################################
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
###############################################################################

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code.
#
# ruff: noqa: E501,F401
# flake8: noqa: E501,F401
# pylint: disable=unused-import,line-too-long
# fmt: off
import baml_py
from enum import Enum
from pydantic import BaseModel, ConfigDict
from typing import Dict, Generic, List, Optional, TypeVar, Union, Literal

from . import types
from .types import Checked, Check

###############################################################################
#
#  These types are used for streaming, for when an instance of a type
#  is still being built up and any of its fields is not yet fully available.
#
###############################################################################

T = TypeVar('T')
class StreamState(BaseModel, Generic[T]):
    value: T
    state: Literal["Pending", "Incomplete", "Complete"]


class Agent(BaseModel):
    agent: Optional[str] = None
    role: Optional[str] = None
    toolbox: Dict[str, Optional["ToolMetadata"]]

class DataSummarizer(BaseModel):
    summary: Optional[str] = None
    messages: Optional["Payload"] = None
    justification: Optional[str] = None

class Metadata(BaseModel):
    UID: Optional[str] = None
    Name: Optional[str] = None
    ID: Optional[str] = None
    DateOfBirth: Optional[str] = None
    Sex: Optional[str] = None
    Species: Optional[str] = None
    Origin: Optional[str] = None
    Facility: Optional[str] = None
    Notes: Optional[str] = None
    Contact: Optional[str] = None
    Scientist: Optional[str] = None
    Publish_uri: Optional[str] = None
    CoScientist: Optional[str] = None
    Treatment1: Optional[str] = None
    Treatment1Type: Optional[str] = None
    Treatment1Route: Optional[str] = None
    Treatment1Date: Optional[str] = None
    Treatment1Dose: Optional[str] = None
    Treatment1DoseUnits: Optional[str] = None
    Treatment2: Optional[str] = None
    Treatment2Type: Optional[str] = None
    Treatment2Route: Optional[str] = None
    Treatment2Date: Optional[str] = None
    Treatment2Dose: Optional[str] = None
    Treatment2DoseUnits: Optional[str] = None
    NecropsyDate: Optional[str] = None
    Cohort: Optional[str] = None
    Supplier: Optional[str] = None
    Treatment3: Optional[str] = None
    Treatment3Type: Optional[str] = None
    Protocol: Optional[str] = None
    Study: Optional[str] = None
    Funder: Optional[str] = None
    TotalCFU: Optional[str] = None
    LungCFU: Optional[str] = None
    LymphNodeCFU: Optional[str] = None
    TotalPathologyScore: Optional[str] = None
    LungPathologyScore: Optional[str] = None
    LymphNodePathologyScore: Optional[str] = None
    CFUUnits: Optional[str] = None
    AlternativeID: Optional[str] = None
    StudyDesign: Optional[str] = None
    Link_StudyDesign: Optional[str] = None
    NewGranulomaCount: Optional[str] = None
    nhp_id: Optional[str] = None
    LINK: Optional[str] = None
    START_DATE: Optional[str] = None
    STOP_DATE: Optional[str] = None
    TYPE: Optional[str] = None
    PATIENT_ID: Optional[str] = None
    EVENT_TYPE: Optional[str] = None
    STUDY_DESIGN_NOTES: Optional[str] = None
    DOSE: Optional[str] = None
    TREATMENT_PARENT: Optional[str] = None
    ORGAN_DETAIL: Optional[str] = None
    ORGAN: Optional[str] = None
    TREATMENT: Optional[str] = None
    CFU: Optional[str] = None
    NAME: Optional[str] = None
    DOSE_UNITS: Optional[str] = None
    SAMPLE_ID: Optional[str] = None
    ROUTE: Optional[str] = None
    PARENT: Optional[str] = None
    Treatment3Route: Optional[str] = None
    Treatment3Date: Optional[str] = None
    Treatment3Dose: Optional[str] = None
    Treatment3DoseUnits: Optional[str] = None

class Navigator(BaseModel):
    agent: Optional["Agent"] = None
    next_tool: Optional[str] = None
    tool_args: List[Optional[str]]
    justification: Optional[str] = None

class Payload(BaseModel):
    system_message: Optional[str] = None
    user_query: Optional[str] = None
    aggregatedMessages: List[Optional[str]]
    resource: Optional["ResourceBox"] = None

class QueryParser(BaseModel):
    parsed_query: Optional[str] = None
    tasks: List[Optional[str]]
    justification: Optional[str] = None

class ResourceBox(BaseModel):
    sample_metadata: List["Metadata"]
    protocolUrl: Optional[str] = None
    sampleUrl: Optional[str] = None
    UIDs: List[Optional[str]]

class Responder(BaseModel):
    Next_worker: Optional["Agent"] = None
    justification: Optional[str] = None

class ResponseFormatter(BaseModel):
    formattedResponse: Optional[str] = None
    name: Optional[str] = None
    messages: Optional["Payload"] = None
    justification: Optional[str] = None

class Supervisor(BaseModel):
    Next_worker: Optional["Agent"] = None
    justification: Optional[str] = None

class ToolMetadata(BaseModel):
    doc: Optional[str] = None
    signature: Optional[str] = None

class Validator(BaseModel):
    name: Optional[str] = None
    Valid: Optional[bool] = None
    Clarifying_Question: Optional[str] = None
    justification: Optional[str] = None
    response: Optional["Payload"] = None
